version: '3.9'

services:
  backend:
    build:
      context: ./backend
      target: 'develop-stage'
    ports:
      - "8088:8088"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x run"

volumes:
  cargo-cache: null
  target-cache: null
